define(function(require) {
	/** *只需要维护该对象** */
	var lang = {
		zh_CN : {
			"please.select":"请选择",
			"browse":"上传",
			//Business
			"fail.delete.publish":"不能删除已发布记录！",
			"fail.modify.publish":"不能修改已发布记录！",
			"fail.modify.audit":"不能修改已审核记录！",
			"fail.delete.audit":"不能删除已审核记录!",
			//Dialog
			"confirm":"<span class='iconfont icon-yes'></span>确定",
			"cancel":"<span style='transform:rotateY(180deg)' class='iconfont icon-return'></span>取消",
			"prompt":"<span class='iconfont icon-info'></span>&nbsp;提示",
			//Grid
			"refresh":"刷新",
			add:"录入",
			edit:"修改",
			view:"查看",
			"delete":"删除",
			"export":"导出",
			"copy":"拷贝",
			delSuccess:"删除成功!",
			delFail:"删除失败!",
			copySuccess:"拷贝成功!",
			copyFail:"拷贝失败!",
			select:"请选择一条记录!",
			ifDel:'是否删除?',
			//Paper
			"page":"页",
			"total":"共",
			"record":"条记录",
			"each.page":"每页",
			"item":"条",
			"jump":" 跳转",
			//Input
			nullwarning:"该字段不能为空！",
			maxLen:"输入字符长度不能超过:",
			minLen:"输入字符长度不能小于:",
			date:"请输入正确的日期格式",
			datetime:"请输入正确的时间格式",
			digits:"请输入正确的数字格式",
			money:"请输入正确的金钱格式",
			email:"请输入正确的邮箱格式",
			number:"请输入正确的数字格式",
			phone:"请输入正确的电话格式",
			mobile:"请输入正确的电话格式",
			tel:"请输入正确的电话格式",
			qq:"请输入正确的QQ格式",
			"int":"请输入正确的整型格式",
			"double":"请输入正确的双精度格式",
			post:"请输入正确的邮编格式",
			url:"请输入正确的URL格式",
			password:"请输入正确的密码格式",
			"char":"请输入正确的字符格式",
			en:"请输入正确的英文格式",
			cardno:"请输入正确的身份证格式",
			cn:"请输入正确的中文格式",
			chinesechar:"请输入正确的中文字符格式",
			stringcheck:"请输入只能包含中文、英文、数字、下划线等字符格式",
			stringfilter:"请输入中英文特殊字符，除英文'-_'字符格式",
			specialchar:"请输入中英文特殊字符，除英文'-_'字符格式"
		},
		en_US : {
			"please.select":"Please Select",
			"browse":"Browse",
			//Business
			"fail.delete.publish":"Can not delete recorded!",
			"fail.modify.publish":"Can not modify published records!",
			"fail.modify.audit":"Can not modify the audit record!",
			"fail.delete.audit":"Can not delete the audited records!",
			//Dialog
			"confirm":"<span class='iconfont icon-yes'></span>Confirm",
			"cancel":"<span style='transform:rotateY(180deg)' class='iconfont icon-return'></span>Cancel",
			"prompt":"<span class='iconfont icon-info'></span>&nbsp;Prompt",
			//Grid
			"refresh":"Refresh",
			"add":"Add",
			edit:"Edit",
			view:"View",
			"delete":"Delete",
			"export":"Export",
			"copy":"Copy",
			delSuccess:"Success Delete!",
			delFail:"Fail delete!",
			copySuccess:"Success Copy!",
			copyFail:"Fail delete!",
			select:"Please select a record!",
			ifDel:'Whether to delete?',
			//Paper
			"page":"Page",
			"total":"Total",
			"record":"Record",
			"each.page":"Per ",
			"item":"item",
			"jump":" Jump",
			//Input
			nullwarning:"The Field Cannot Be Empty!！",
			maxLen:"Input Character Length Cannot Exceed:" ,
			minLen:"Input Character Length Cannot Be Less Than:",
			date:"Please Enter The Correct Date Format",
			datetime:"lease Enter The Correct Time Format",
			digits:"Please Enter The Correct Digital Format",
			money:"Please Enter The Correct Money Format",
			email:"Please Enter The Correct Email Format",
			number:"Please Enter The Correct Number Format",
			phone:"Please Enter The Correct Phone Format",
			mobile:"Please Enter The Correct Mobile Format",
			tel:"Please Enter The Correct TEL Format",
			qq:"Please Enter The Correct QQ Format",
			"int":"Please Enter The Correct Integer Format",
			"double":"Please Enter The Correct Double Format",
			post:"Please Enter The Correct Post Format",
			url:"Please Enter The Correct URL Format",
			"char":"Please Enter The Correct Char Format",
			password:"Please Enter The Correct Password Format",
			en:"Please Enter The Correct English Format",
			cardno:"Please Enter The Correct CardNo Format",
			cn:"Please Enter The Correct Chinese Format",
			chinesechar:"Please Enter The Correct Chinese Char Format",
			stringcheck:"Please Input Can Only Oontain Chinese, English, Numbers, Underline And Other Character Format",
			stringfilter:"Please Input English Special Characters, In Addition To English'-_'Character Format",
			specialchar:"Please Input English Special Characters, In Addition To English'-_'Character Format"
		}
	};
	/** *** */
	return  lang[Session.langue];
});
